// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5wJ9uN6KJowqaKeCbMQ-DnWdVCyYb7Mg',
    appId: '1:358373943684:web:8ff9a76168b82245b395d1',
    messagingSenderId: '358373943684',
    projectId: 'daylivery-6336b',
    authDomain: 'daylivery-6336b.firebaseapp.com',
    storageBucket: 'daylivery-6336b.appspot.com',
    measurementId: 'G-7TXRWGMSPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQRtEMpKppGKFpZ8FHcYYY5uMAxBY5oNE',
    appId: '1:358373943684:android:ef6270e1054f093cb395d1',
    messagingSenderId: '358373943684',
    projectId: 'daylivery-6336b',
    storageBucket: 'daylivery-6336b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbtE8ZVo34CR-dENn1vWSzeyKvX09EogA',
    appId: '1:358373943684:ios:382f12c2506acf91b395d1',
    messagingSenderId: '358373943684',
    projectId: 'daylivery-6336b',
    storageBucket: 'daylivery-6336b.appspot.com',
    iosBundleId: 'com.example.dayliff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbtE8ZVo34CR-dENn1vWSzeyKvX09EogA',
    appId: '1:358373943684:ios:84c6b6fe7f8f5c39b395d1',
    messagingSenderId: '358373943684',
    projectId: 'daylivery-6336b',
    storageBucket: 'daylivery-6336b.appspot.com',
    iosBundleId: 'com.example.dayliff.RunnerTests',
  );
}
